In [2]:
import pandas as pd
df = pd.read_excel('C:/Place_for_training/project_3/Crime_Data.xlsx')
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,2001-08-27 23:00:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,...,NaN,NaN,26,1182305.0,1881212.0,2001,2015-08-17 15:03:40,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,2001-10-16 16:30:00,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,NaN,NaN,5,1174713.0,1861451.0,2001,2015-08-17 15:03:40,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,2001-09-29 05:35:00,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,...,NaN,NaN,08B,1151878.0,1920763.0,2001,2015-08-17 15:03:40,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,2001-09-12 09:05:00,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,...,NaN,NaN,7,1145544.0,1861043.0,2001,2015-08-17 15:03:40,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,2001-10-18 17:34:00,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,...,NaN,NaN,26,1140670.0,1902673.0,2001,2015-08-17 15:03:40,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [3]:
df_copy = df.copy()
df_copy

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,2001-08-27 23:00:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,...,NaN,NaN,26,1182305.0,1881212.0,2001,2015-08-17 15:03:40,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,2001-10-16 16:30:00,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,NaN,NaN,5,1174713.0,1861451.0,2001,2015-08-17 15:03:40,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,2001-09-29 05:35:00,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,...,NaN,NaN,08B,1151878.0,1920763.0,2001,2015-08-17 15:03:40,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,2001-09-12 09:05:00,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,...,NaN,NaN,7,1145544.0,1861043.0,2001,2015-08-17 15:03:40,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,2001-10-18 17:34:00,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,...,NaN,NaN,26,1140670.0,1902673.0,2001,2015-08-17 15:03:40,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [4]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date                  549999 non-null  datetime64[ns]
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  datetime64[ns]
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 85.0+ MB

In [5]:
df_copy.columns = df_copy.columns.str.replace(" ","_")
df_copy.columns

Index(['ID', 'Case_Number', 'Date', 'Block', 'IUCR', 'Primary_Type',
       'Description', 'Location_Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community_Area', 'FBI_Code', 'X_Coordinate',
       'Y_Coordinate', 'Year', 'Updated_On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [6]:
df_copy['Ward'] = df_copy.groupby('Beat')['Ward'].transform(
    lambda x:x.fillna(x.mode()[0] if not x.mode().empty else pd.NA))
df_copy['Community_Area'] = df_copy['Community_Area'].fillna(df_copy.groupby('Beat')['Community_Area'].transform(
    lambda x: x.mode()[0] if not x.mode().empty else pd.NA)
)
df_copy.dropna(subset=['Ward', 'Community_Area', 'Latitude', 'Location_Description'], inplace=True)
df_copy['Ward'] = df_copy['Ward'].astype(int)
df_copy['Community_Area'] = df_copy['Community_Area'].astype(int)
df_copy = df_copy.drop(columns='Location')
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 541983 entries, 1 to 549998
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    541983 non-null  int64
 1   Case_Number           541983 non-null  object
 2   Date                  541983 non-null  datetime64[ns]
 3   Block                 541983 non-null  object
 4   IUCR                  541983 non-null  object
 5   Primary_Type          541983 non-null  object
 6   Description           541983 non-null  object
 7   Location_Description  541983 non-null  object
 8   Arrest                541983 non-null  bool
 9   Domestic              541983 non-null  bool
 10  Beat                  541983 non-null  int64
 11  District              541983 non-null  int64
 12  Ward                  541983 non-null  int64
 13  Community_Area        541983 non-null  int64
 14  FBI_Code              541983 non-null  object
 15  X_Coordinate          541983 non-null  float64
 16  Y_Coordinate          541983 non-null  float64
 17  Year                  541983 non-null  int64
 18  Updated_On            541983 non-null  datetime64[ns]
 19  Latitude              541983 non-null  float64
 20  Longitude             541983 non-null  float64
dtypes: bool(2), datetime64[ns](2), float64(4), int64(6), object(7)
memory usage: 83.7+ MB

In [8]:
df_copy = df_copy[df_copy['Latitude'] > 40]
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 541944 entries, 1 to 549998
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    541944 non-null  int64
 1   Case_Number           541944 non-null  object
 2   Date                  541944 non-null  datetime64[ns]
 3   Block                 541944 non-null  object
 4   IUCR                  541944 non-null  object
 5   Primary_Type          541944 non-null  object
 6   Description           541944 non-null  object
 7   Location_Description  541944 non-null  object
 8   Arrest                541944 non-null  bool
 9   Domestic              541944 non-null  bool
 10  Beat                  541944 non-null  int64
 11  District              541944 non-null  int64
 12  Ward                  541944 non-null  int64
 13  Community_Area        541944 non-null  int64
 14  FBI_Code              541944 non-null  object
 15  X_Coordinate          541944 non-null  float64
 16  Y_Coordinate          541944 non-null  float64
 17  Year                  541944 non-null  int64
 18  Updated_On            541944 non-null  datetime64[ns]
 19  Latitude              541944 non-null  float64
 20  Longitude             541944 non-null  float64
dtypes: bool(2), datetime64[ns](2), float64(4), int64(6), object(7)
memory usage: 83.7+ MB

In [ ]:
df_copy.to_csv('Cleaned_Chicago_Crime.csv', index=False)